CREATE SEQUENCE IF NOT EXISTS user_sequence START WITH 10000 INCREMENT BY 1;

CREATE TABLE refresh_tokens
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    jti             UUID                                    NOT NULL,
    revoked         BOOLEAN                                 NOT NULL,
    replaced_by_jti UUID,
    expires_at      TIMESTAMP                                NOT NULL,
    created_at      TIMESTAMP                                NOT NULL,
    CONSTRAINT pk_refreshtokens PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id        BIGINT NOT NULL,
    role_name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT NOT NULL,
    email         VARCHAR(255),
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    phone_number  VARCHAR(255),
    password_hash VARCHAR(255),
    updated_at    TIMESTAMP,
    created_at    TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    auth_user_id BIGINT NOT NULL,
    roles_id     BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (auth_user_id, roles_id)
);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refreshtokens_jti UNIQUE (jti);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users_roles
    ADD CONSTRAINT uc_users_roles_roles UNIQUE (roles_id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_auth_user FOREIGN KEY (auth_user_id) REFERENCES users (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_user_roles FOREIGN KEY (roles_id) REFERENCES roles (id);


INSERT INTO roles(id, role_name)
VALUES
    (1, 'SUPER_ADMIN'),
    (2, 'ADMIN'),
    (3, 'USER');

INSERT INTO users (
    id            ,
    email         ,
    first_name    ,
    last_name     ,
    phone_number  ,
    password_hash ,
    created_at
)
VALUES (
           nextval('user_sequence'),
           'introtech@givmail.com',
           'Intro',
           'Tech',
           null,
           '$2a$12$.YFXvUYn8cGBvw6bOVQzR.HOCnBpLUwfk09N7qFyRfVMB/z1QdAvG',
           now()
       )
ON CONFLICT (email) DO NOTHING;

INSERT INTO users_roles (auth_user_id, roles_id)
VALUES (
           currval('user_sequence'),
           1
       )