CREATE SEQUENCE IF NOT EXISTS user_sequence START WITH 10000 INCREMENT BY 1;

CREATE TABLE client
(
    id          BIGINT NOT NULL,
    client_name VARCHAR(255),
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    jti             UUID                                    NOT NULL,
    revoked         BOOLEAN                                 NOT NULL,
    replaced_by_jti UUID,
    expires_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refreshtokens PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255),
    client    VARCHAR,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT  NOT NULL,
    email         VARCHAR(255),
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    phone_number  VARCHAR(255),
    password_hash VARCHAR(255),
    client        VARCHAR NOT NULL,
    enabled       BOOLEAN NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    auth_user_id BIGINT NOT NULL,
    roles_id     BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (auth_user_id, roles_id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_2c04380fee986f780f477d548 UNIQUE (role_name, client);

ALTER TABLE client
    ADD CONSTRAINT uc_client_client_name UNIQUE (client_name);

ALTER TABLE users
    ADD CONSTRAINT uc_fb226dba3707fb3acf5a17828 UNIQUE (email, client);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refreshtokens_jti UNIQUE (jti);

ALTER TABLE roles
    ADD CONSTRAINT FK_ROLES_ON_CLIENT FOREIGN KEY (client) REFERENCES client (client_name);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_CLIENT FOREIGN KEY (client) REFERENCES client (client_name);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_auth_user FOREIGN KEY (auth_user_id) REFERENCES users (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_user_roles FOREIGN KEY (roles_id) REFERENCES roles (id);


INSERT INTO client (id, client_name)
VALUES
    (1, 'introtech-service')
ON CONFLICT (client_name) DO NOTHING;

INSERT INTO roles(id, role_name)
VALUES
    (999, 'SUPER_ADMIN'),
    (998, 'ADMIN'),
    (997, 'USER');

INSERT INTO users (
    id         ,
    email        ,
    first_name  ,
    last_name     ,
    phone_number  ,
    password_hash ,
    client        ,
    enabled     ,
    updated_at  ,
    created_at
)
VALUES (
           nextval('user_sequence'),
           'introtech@givmail.com',
           'Intro',
           'Tech',
           null,
           '$2a$12$.YFXvUYn8cGBvw6bOVQzR.HOCnBpLUwfk09N7qFyRfVMB/z1QdAvG',
              'introtech-service',
        true,
        now(),
        now()
       )
ON CONFLICT (email, client) DO NOTHING;

INSERT INTO users_roles (auth_user_id, roles_id)
VALUES (
           currval('user_sequence'),
           999
       )