name: Introtech Microservices

services:

  discovery-service:
    image: oorezy/discovery-service:latest
    build:
      context: .
      dockerfile: ./DiscoveryService/Dockerfile
    container_name: discovery-service
    ports:
      - "7000:7000"
    environment:
      JAVA_OPTS: "-Xms64m -Xmx128m"
    volumes:
      - ${HOME_DIR}:/INTROTECH
    restart: always

  gateway-service:
    image: oorezy/gateway-service:latest
    build:
      context: .
      dockerfile: ./GatewayService/Dockerfile
    container_name: gateway-service
    ports:
      - "7001:7001"
    environment:
      JAVA_OPTS: "-Xms128m -Xmx256m"
    volumes:
      - ${HOME_DIR}:/INTROTECH
    depends_on:
      - discovery-service
    restart: always

  authentication-service:
    image: oorezy/authentication-service:latest
    build:
      context: .
      dockerfile: ./AuthenticationService/Dockerfile
    container_name: authentication-service
    ports:
      - "7002:7002"
    environment:
      JAVA_OPTS: "-Xms128m -Xmx256m"
    volumes:
      - ${HOME_DIR}:/INTROTECH
    depends_on:
      - discovery-service
    restart: always

  introtech-service:
    image: oorezy/introtech-service:latest
    build:
      context: .
      dockerfile: ./IntrotechService/Dockerfile
    container_name: introtech-service
    ports:
      - "7004:7004"
    environment:
      JAVA_OPTS: "-Xms128m -Xmx384m"
    volumes:
      - ${HOME_DIR}:/INTROTECH
    depends_on:
      - discovery-service
    restart: always

  frontend:
    image: oorezy/client-service:latest
    build: ./ClientService
    container_name: client-service
    ports:
      - "4200:80"
    restart: always